function selection = get_selected_problem
    f=figure;
    set(f,'Menu','none','Toolbar','none');
    h=struct;
    h.f=f;
    h.explanation=uicontrol('Parent',f,...
        'Style','text',...
        'String','Please select the problem.',...
        'Units','Normalized',...
        'FontSize',14,...
        'Position',[0.2 0.8 0.6 0.075]);
    h.outputValuesButton=uicontrol('Parent',f,...
        'Style','pushbutton',...
        'String','Asymmetric Traveling Salesman Problem',...
        'Callback',@atsp,...
        'FontSize',10,...
        'Units','Normalized',...
        'Position',[0.25 0.7 0.5 0.07]);
    h.outputValuesButton=uicontrol('Parent',f,...
        'Style','pushbutton',...
        'String','Graph Coloring Problem',...
        'Callback',@gc,...
        'FontSize',10,...
        'Units','Normalized',...
        'Position',[0.25 0.6 0.5 0.07]);
    h.outputValuesButton=uicontrol('Parent',f,...
        'Style','pushbutton',...
        'String','Graph Partitioning Problem',...
        'Callback',@gp,...
        'FontSize',10,...
        'Units','Normalized',...
        'Position',[0.25 0.5 0.5 0.07]);
    h.outputValuesButton=uicontrol('Parent',f,...
        'Style','pushbutton',...
        'String','Hamiltonian Cycle Problem',...
        'Callback',@hcp,...
        'FontSize',10,...
        'Units','Normalized',...
        'Position',[0.25 0.4 0.5 0.07]);
    h.outputValuesButton=uicontrol('Parent',f,...
        'Style','pushbutton',...
        'String','Max Cut Problem',...
        'Callback',@mc,...
        'FontSize',10,...
        'Units','Normalized',...
        'Position',[0.25 0.3 0.5 0.07]);
    h.outputValuesButton=uicontrol('Parent',f,...
        'Style','pushbutton',...
        'String','Set Packing Problem',...
        'Callback',@sp,...
        'FontSize',10,...
        'Units','Normalized',...
        'Position',[0.25 0.2 0.5 0.07]);
    h.outputValuesButton=uicontrol('Parent',f,...
        'Style','pushbutton',...
        'String','Vertex Cover Problem',...
        'Callback',@vc,...
        'FontSize',10,...
        'Units','Normalized',...
        'Position',[0.25 0.1 0.5 0.07]);
    guidata(h.f,h);
    uiwait(h.f);
    try
        h=guidata(h.f);
        selection=h.value;
        close(h.f);
    catch
        selection = 8;
    end
end
function atsp(hObject,evnt)
    h=guidata(hObject);
    h.value = 1;
    guidata(h.f,h)
    uiresume(h.f)
end
function gc(hObject,evnt)
    h=guidata(hObject);
    h.value = 2;
    guidata(h.f,h)
    uiresume(h.f)
end
function gp(hObject,evnt)
    h=guidata(hObject);
    h.value = 3;
    guidata(h.f,h)
    uiresume(h.f)
end
function hcp(hObject,evnt)
    h=guidata(hObject);
    h.value = 4;
    guidata(h.f,h)
    uiresume(h.f)
end
function mc(hObject,evnt)
    h=guidata(hObject);
    h.value = 5;
    guidata(h.f,h)
    uiresume(h.f)
end
function sp(hObject,evnt)
    h=guidata(hObject);
    h.value = 6;
    guidata(h.f,h)
    uiresume(h.f)
end
function vc(hObject,evnt)
    h=guidata(hObject);
    h.value = 7;
    guidata(h.f,h)
    uiresume(h.f)
end