function str=get_input_file
    f=figure;
    set(f,'Menu','none','Toolbar','none')
    h=struct;
    h.f=f;
    h.editfield=uicontrol('Parent',f,...
        'Style','edit',...
        'HorizontalAlignment','left',...
        'max',1,...
        'Units','Normalized',...
        'FontSize',12,...
        'Position',[0.075 0.6 0.5 0.1]);
    h.explanation=uicontrol('Parent',f,...
        'Style','text',...
        'String','Please type the input file name below',...
        'Units','Normalized',...
        'FontSize',12,...
        'Position',[0.075 0.7 0.5 0.1]);
    h.outputValuesButton=uicontrol('Parent',f,...
        'Style','pushbutton',...
        'String','Enter',...
        'FontSize',12,...
        'Callback',@outputValues,...
        'Units','Normalized',...
        'Position',[0.6 0.6 0.3 0.1]);
    guidata(h.f,h)
    uiwait(h.f)
    try
        h=guidata(h.f);
        str=h.values;
        close(h.f);
    catch
        str='';
    end
end
function testValues(hObject,evnt) 
    h=guidata(hObject);
    str=get(h.editfield,'String');
    if isempty(str)
        h.values='';
    else
        h.values=str;
    end
    guidata(h.f,h)
end
function outputValues(hObject,evnt)
    h=guidata(hObject);
    testValues(hObject)%will store the valid values in h.values
    uiresume(h.f)
end